# Bibliotecas

In [ ]:
import pandas as pd
import yahooquery as yq
from datetime import datetime

# Leitura e tratamento dos dados

DATA COM: É dada que se pode comprar para receber o pagamento referido na linha

DY: É o valor do dividendo sobre o valor da ação

In [3]:
planilha = pd.read_csv(r".\Dados Capturados\(Cru) Dividendos pagos por data (2021-2025).csv")
planilha

      ATIVO          VALOR    DATA COM DATA PAGAMENTO       TIPO     DY
0     BBDC3  R$ 0,01724983  01/12/2020     04/01/2021        JCP  0,08%
1     BBDC4  R$ 0,01897481  01/12/2020     04/01/2021        JCP  0,08%
2     ITSA4  R$ 0,02000000  30/11/2020     04/01/2021  Dividendo  0,19%
3     ITUB4  R$ 0,01500000  30/11/2020     04/01/2021  Dividendo  0,05%
4     BBDC3  R$ 0,37752123  28/12/2020     07/01/2021        JCP  1,51%
...     ...            ...         ...            ...        ...    ...
1458  CMIG4  R$ 0,08778000  26/03/2024     30/12/2025        JCP  0,71%
1459  CMIG4  R$ 0,32940590  30/04/2025     30/12/2025  Dividendo  3,20%
1460  CMIG4  R$ 0,09790376  23/12/2024     30/12/2025        JCP  0,87%
1461  MULT3  R$ 0,40926725  30/12/2024     30/12/2025        JCP  1,94%
1462  HYPE3  R$ 0,09735000  23/05/2024     31/12/2025        JCP  0,32%

[1463 rows x 6 columns]

In [10]:
planilha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1463 entries, 0 to 1462
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ATIVO           1463 non-null   object
 1   VALOR           1463 non-null   object
 2   DATA COM        1463 non-null   object
 3   DATA PAGAMENTO  1463 non-null   object
 4   TIPO            1463 non-null   object
 5   DY              1463 non-null   object
dtypes: object(6)
memory usage: 68.7+ KB

In [11]:
planilha["VALOR"] = planilha["VALOR"].apply(lambda x: x.replace("R$ ", "").replace(",", '.'))
planilha["VALOR"] = planilha["VALOR"].apply(lambda x: float(x.split('.')[0] + '.' + x.split('.')[1][:2]))
planilha["DATA COM"] =  planilha["DATA COM"].apply(lambda x: pd.to_datetime(x.replace('/', '-'), format='%d-%m-%Y'))
planilha["DATA PAGAMENTO"] =  planilha["DATA PAGAMENTO"].apply(lambda x: pd.to_datetime(x.replace('/', '-'), format='%d-%m-%Y'))
planilha["DY"] =  planilha["DY"].apply(lambda x: float(x.replace(',', '.').replace('%', '')))
planilha

      ATIVO  VALOR   DATA COM DATA PAGAMENTO       TIPO    DY
0     BBDC3   0.01 2020-12-01     2021-01-04        JCP  0.08
1     BBDC4   0.01 2020-12-01     2021-01-04        JCP  0.08
2     ITSA4   0.02 2020-11-30     2021-01-04  Dividendo  0.19
3     ITUB4   0.01 2020-11-30     2021-01-04  Dividendo  0.05
4     BBDC3   0.37 2020-12-28     2021-01-07        JCP  1.51
...     ...    ...        ...            ...        ...   ...
1458  CMIG4   0.08 2024-03-26     2025-12-30        JCP  0.71
1459  CMIG4   0.32 2025-04-30     2025-12-30  Dividendo  3.20
1460  CMIG4   0.09 2024-12-23     2025-12-30        JCP  0.87
1461  MULT3   0.40 2024-12-30     2025-12-30        JCP  1.94
1462  HYPE3   0.09 2024-05-23     2025-12-31        JCP  0.32

[1463 rows x 6 columns]

In [12]:
planilha.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1463 entries, 0 to 1462
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ATIVO           1463 non-null   object
 1   VALOR           1463 non-null   float64
 2   DATA COM        1463 non-null   datetime64[ns]
 3   DATA PAGAMENTO  1463 non-null   datetime64[ns]
 4   TIPO            1463 non-null   object
 5   DY              1463 non-null   float64
dtypes: datetime64[ns](2), float64(2), object(2)
memory usage: 68.7+ KB

In [16]:
pd.unique(planilha.loc[:, "ATIVO"])

array(['BBDC3', 'BBDC4', 'ITSA4', 'ITUB4', 'HYPE3', 'B3SA3', 'BEEF3',
       'VBBR3', 'ISAE4', 'TIMS3', 'ABEV3', 'MRVE3', 'EGIE3', 'SANB11',
       'BPAC11', 'RENT3', 'ELET3', 'ELET6', 'BBSE3', 'BBAS3', 'FLRY3',
       'RDOR3', 'WEGE3', 'UGPA3', 'VALE3', 'GGBR4', 'GOAU4', 'ENGI11',
       'POMO4', 'PSSA3', 'PETR3', 'PETR4', 'CPLE6', 'HAPV3', 'MOTV3',
       'MRFG3', 'MGLU3', 'LREN3', 'BRAP4', 'CSNA3', 'SLCE3', 'VIVA3',
       'ALOS3', 'CSAN3', 'TOTS3', 'TAEE11', 'RADL3', 'USIM5', 'ASAI3',
       'DIRR3', 'CYRE3', 'PCAR3', 'CPFE3', 'SBSP3', 'CMIG4', 'VIVT3',
       'AZZA3', 'CURY3', 'CMIN3', 'IRBR3', 'MULT3', 'KLBN11', 'CXSE3',
       'YDUQ3', 'BRKM5', 'EQTL3', 'STBP3', 'VAMO3', 'SUZB3', 'RAIZ4',
       'IGTI11', 'RECV3', 'AURE3', 'RAIL3', 'SMFT3', 'PRIO3', 'BRAV3',
       'BRFS3', 'EMBR3', 'COGN3', 'CEAB3'], dtype=object)

In [13]:
planilha.to_csv(r".\Dados Modelados\Dividendos pagos por data (2021-2025).csv", index=False)

# Criando histórico de preços

In [ ]:
ativos = pd.unique(planilha.loc[:, "ATIVO"]).tolist()

In [ ]:
lista_tickers = []
for ativo in ativos:
    lista_tickers.append((ativo,yq.Ticker(ativo+'.SA')))

In [ ]:
idx = 0
lista_precos_historicos = []
for nome, ticker in lista_tickers:
    lista_precos_historicos.append(ticker.history(period='5y',interval='1mo'))
    lista_precos_historicos[idx].assign(ativo=nome)
    idx += 1

In [ ]:
df_historico_ativos = pd.concat(lista_precos_historicos)

In [ ]:
df_historico_ativos['Ativo'] = df_historico_ativos.index.get_level_values(0)
df_historico_ativos['Data'] = df_historico_ativos.index.get_level_values(1)

In [ ]:
for idx, line in df_historico_ativos.iterrows():
    df_historico_ativos.loc[idx,'Ativo'] = df_historico_ativos.loc[idx,'Ativo'].split('.')[0]

In [ ]:
df_historico_ativos['Data'] = pd.to_datetime(df_historico_ativos['Data'], format='%Y-%m-%d')

In [ ]:
df_historico_ativos['Data'] = df_historico_ativos['Data'].apply(lambda x: x.strftime('%d-%m-%Y'))

In [ ]:
df_historico_ativos.to_csv('Dados Modelados/historico_ativos.csv', index=False)

# Criando setor, insdustria e recomendação

In [ ]:
idx = 0
ativos_se_in_re = pd.DataFrame()
for nome, ticker in lista_tickers:
    ativos_se_in_re.loc[idx, 'ATIVO'] = nome
    ativos_se_in_re.loc[idx, 'SETOR'] = ticker.asset_profile[nome+'.SA']['industry']
    ativos_se_in_re.loc[idx, 'INDUSTRIA'] = ticker.asset_profile[nome+'.SA']['sector']
    ativos_se_in_re.loc[idx, 'DATA'] = datetime.now().strftime('%d-%m-%Y')
    ativos_se_in_re.loc[idx, 'RECOMENDACAO'] = ticker.financial_data[nome+'.SA']['recommendationKey']
    idx += 1

In [ ]:
ativos.to_csv('Dados Modelados/Ativos.csv', index=False)